### ISSUE TITLE
コマンドのjsonの作成

### ISSUE THREAD

**Issue by sizumita** [virtualCrypto-discord/virtualCrypto2#1]
botのコマンドとしてdiscordに送信するjsonの作成

https://github.com/virtualCrypto-discord/virtualCrypto/wiki/Commands に存在するコマンドの移植+スラッシュコマンドに合わせた対応

**Comment by tignear** [comment]
discord-slash-command-schema-builderみたいなのをライブラリとして作ると良さげ

**Comment by sizumita** [comment]
よさげ。頑張ってみる

**Comment by sizumita** [comment]
ライブラリというよりはファイルとして作った方が良さそう、管理が面倒になる
