### ISSUE TITLE
謎のラベル何

### ISSUE THREAD

**Issue by tignear** [virtualCrypto-discord/virtualCrypto2#214]

**Comment by sizumita** [comment]
遊び心だったんです....()

**Comment by sizumita** [comment]
消してもらっても大丈夫です

**Comment by tignear** [comment]
いや遊び心はいいんだけどそのタグは何を表してるのかわかりにくい。
できたらいいなの方は優先度低いっていうタグなら私はそのissueやる気があるし優先度は高い認識なので不適。
力こそパワーはよくわかんない。

**Comment by tignear** [comment]
あ。説明書いてあったわ。ごめん
